❌ Failed to install packages: Command '['venv\\Scripts\\python.exe', '-m', 'pip', 'install', '-r', 'requirements-windows.txt']' returned non-zero exit status 1.
Error output: WARNING: Ignoring invalid distribution ~ip (C:\Users\Admin\Phishing-detection-platform\venv\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Admin\Phishing-detection-platform\venv\Lib\site-packages)
  error: subprocess-exited-with-error

  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1

  [45 lines of output]
  Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "C:\Users\Admin\Phishing-detection-platform\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
      main()
      ~~~~^^
    File "C:\Users\Admin\Phishing-detection-platform\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Admin\Phishing-detection-platform\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 175, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-qpzus6a4\overlay\Lib\site-packages\setuptools\build_meta.py", line 374, in prepare_metadata_for_build_wheel
      self.run_setup()
      ~~~~~~~~~~~~~~^^
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-qpzus6a4\overlay\Lib\site-packages\setuptools\build_meta.py", line 512, in run_setup
      super().run_setup(setup_script=setup_script)
      ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-qpzus6a4\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
      exec(code, locals())
      ~~~~^^^^^^^^^^^^^^^^
    File "<string>", line 633, in <module>
    File "<string>", line 627, in setup_package
    File "<string>", line 554, in configure_extension_modules
    File "C:\Users\Admin\AppData\Local\Temp\pip-install-huz2sk3s\scikit-learn_b36d0307b6154964a1684742fbbbb96c\sklearn\_build_utils\__init__.py", line 46, in cythonize_extensions
      basic_check_build()
      ~~~~~~~~~~~~~~~~~^^
    File "C:\Users\Admin\AppData\Local\Temp\pip-install-huz2sk3s\scikit-learn_b36d0307b6154964a1684742fbbbb96c\sklearn\_build_utils\pre_build_helpers.py", line 73, in basic_check_build
      compile_test_program(code)
      ~~~~~~~~~~~~~~~~~~~~^^^^^^
    File "C:\Users\Admin\AppData\Local\Temp\pip-install-huz2sk3s\scikit-learn_b36d0307b6154964a1684742fbbbb96c\sklearn\_build_utils\pre_build_helpers.py", line 31, in compile_test_program
      ccompiler.compile(
      ~~~~~~~~~~~~~~~~~^
          ["test_program.c"], output_dir="objects", extra_postargs=extra_postargs
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      )
      ^
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-qpzus6a4\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\msvc.py", line 384, in compile
      self.initialize()
      ~~~~~~~~~~~~~~~^^
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-qpzus6a4\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\msvc.py", line 294, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-qpzus6a4\overlay\Lib\site-packages\setuptools\_distutils\compilers\C\msvc.py", line 155, in _get_vc_env
      raise DistutilsPlatformError(
      ...<3 lines>...
      )
  distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


❌ Setup failed. Please check the error messages above.